Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [1]:
import numpy as np

In [2]:
a=np.arange(20)
display(a)
a.shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

(20,)

In [3]:
a=a.reshape(2,10)
display(a)
a.shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

(2, 10)

Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [4]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

arr[arr%2!=0]

array([1, 3, 5, 7, 9])

Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [5]:
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [6]:
arr=np.arange(10)
display(np.where((arr%2!=0),-1,arr))
display(arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [7]:
arr1=np.arange(20).reshape(5,4)
display(arr1)
arr2=np.arange(20,40).reshape(5,4)
display(arr2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [8]:
display(np.vstack((arr1,arr2)))
display(np.hstack((arr1,arr2)))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31],
       [12, 13, 14, 15, 32, 33, 34, 35],
       [16, 17, 18, 19, 36, 37, 38, 39]])

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
display(a)
display(b)
display(np.vstack((a,b)))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [10]:
a=np.arange(10).reshape(2,-1)
display(a)
b=np.repeat(1,10).reshape(2,-1)
display(b)
np.hstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [11]:
a = np.array([1,2,3])
aa=np.repeat(a,3)
bb=np.tile(a,3)
display(np.hstack((aa,bb)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```

In [12]:
a = np.array([1,2,3,4,5])
display(a)
b = np.array([5,6,7,8,9])
display(b)
C = np.array(list(filter(lambda x: x not in b,a)))
C


array([1, 2, 3, 4, 5])

array([5, 6, 7, 8, 9])

array([1, 2, 3, 4])

In [13]:
display(a)
display(np.insert(a,1,2222))
display(np.append(a,3333))
display(np.delete(a,1))

array([1, 2, 3, 4, 5])

array([   1, 2222,    2,    3,    4,    5])

array([   1,    2,    3,    4,    5, 3333])

array([1, 3, 4, 5])

Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# np.where(a%2==0) #give indices
np.where(a==b) #give indices

(array([1, 3, 5, 7], dtype=int64),)

Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```

In [15]:
arr = np.arange(9).reshape(3,3)
display(arr)
arr[:,[0,1]]=arr[:,[1,0]]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```

In [16]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
display(a)
a=np.where((a>30),30,a)
a=np.where(a<10,10,a)

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [17]:
a

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```


In [23]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [28]:
np.random.seed(3)
a=np.random.randint(1,20,5)
display(a)
np.sort

array([11,  4,  9,  1, 11])

<function numpy.sort(a, axis=-1, kind=None, order=None)>

Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [29]:
np.random.seed(3)
# a=np.random.randint(1,10,size=(5,3))
a=np.random.randint(1,10, [5,3])
display(a)

array([[9, 4, 9],
       [9, 1, 6],
       [4, 6, 8],
       [7, 1, 5],
       [8, 9, 2]])

In [30]:
v=a.min(axis=1)
v

array([4, 1, 4, 1, 2])

In [31]:
k=a.max(axis=1)
k

array([9, 9, 8, 7, 9])

In [32]:
v/k

array([0.44444444, 0.11111111, 0.5       , 0.14285714, 0.22222222])

In [33]:
a=np.arange(10).reshape(2,5)
display(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
display(np.sum(a,axis=0))
display(np.sum(a,axis=1))
display(np.min(a,axis=0))
display(np.min(a,axis=1))

array([ 5,  7,  9, 11, 13])

array([10, 35])

array([0, 1, 2, 3, 4])

array([0, 5])

Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

In [35]:
def duplicates(a):
    uniques = np.unique(a)
    result = []
    for i in a:
        if i not in uniques:
            result.append(True)
        else:
            result.append(False)
            uniques = np.delete(uniques, np.where(uniques == i))
    return result


np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
print(duplicates(a))

Array:  [0 0 3 0 2 4 2 2 2 2]
[False, True, False, True, False, False, True, True, True, True]


In [36]:
def dupNum(arr):
    uniqueNum=np.unique(arr)
    result=[]
    for i in arr:
        if i in uniqueNum:
            result.append(False)
            uniqueNum=np.delete(uniqueNum,np.where(i==uniqueNum))
        else:
            result.append(True)
    return result
np.random.seed(2)
arr=np.random.randint(0,5,10)
print('Array arr',arr)
dupNum(arr)

Array arr [0 0 3 2 3 0 2 1 3 2]


[False, True, False, False, True, True, True, False, True, True]

In [37]:
c=np.array([3,3,4,5,6,2])
display(c,c.dtype)
d=np.array([3,4,2,5,6,1])
display(d,d.dtype)
display(np.delete(c,np.where(c==3)))
display(np.where(c==d))
display(np.where(c==3))

array([3, 3, 4, 5, 6, 2])

dtype('int32')

array([3, 4, 2, 5, 6, 1])

dtype('int32')

array([4, 5, 6, 2])

(array([0, 3, 4], dtype=int64),)

(array([0, 1], dtype=int64),)

Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [38]:
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
display(a)
d=np.isfinite(a)
# d=np.isnan(a) #it will give true where number is not found
display(d)
a[d]

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

array([ True,  True,  True, False,  True,  True,  True, False])

array([1., 2., 3., 5., 6., 7.])

Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

In [39]:
def peak(a):
    result=[]
    for i in range(1,(len(a)-1)):
#         print(i)
#         print(a[i])
        if(a[i]>a[i-1] and a[i]>a[i+1]):
            result.append(i)
    print(result)
a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) 
display(a)
peak(a)

array([1, 3, 7, 1, 2, 6, 0, 1])

[2, 5]


In [40]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a.shape=(2,4)
display(a)
a.sum(axis=0)
a.sum(axis=1)

array([[1, 3, 7, 1],
       [2, 6, 0, 1]])

array([12,  9])

Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

In [46]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
display(a_2d)
b_1d = np.array([1,1,1])
display(b_1d)
display(np.subtract(a_2d,b_1d))
display(a_2d)
display(a_2d.sum())
display(a_2d.cumsum())

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

array([1, 1, 1])

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

36

array([ 3,  6,  9, 13, 17, 21, 26, 31, 36], dtype=int32)

Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```

In [47]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
d=np.where(x==1,True,False)
c=x[d]
display(c)
for i in range(1,len(c)):
    print(c[5])
    break

array([1, 1, 1, 1, 1, 1, 1])

1


Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [48]:
display(np.arange(5,15))
display(np.linspace(5,15,3))
display(np.arange(5,15,4))

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 5., 10., 15.])

array([ 5,  9, 13])

Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]

In [44]:
arr = np.arange(15)
arr.strides

(4,)